# Fusion of ratings and movies

In [11]:
import pandas as pd
movies_df_mb = pd.read_parquet('../data/processed/movies_df.parquet')
ratings_df = df = pd.read_parquet('../data/processed/ratings_df.parquet')
ratings_movies_df = ratings_df.merge(movies_df_mb, on='movieId', how='left')

In [12]:
print("structure of ratings_df and of ratings_movies_df:", ratings_df.shape, ratings_movies_df.shape)          # même nombre de lignes
print("number of missing values in columns of ratings_movies_df:", ratings_movies_df.isna().sum())    
print("total number of missing values in ratings_movies_df:", ratings_movies_df.isna().sum().sum()) 
display(ratings_movies_df.head(5))

structure of ratings_df and of ratings_movies_df: (2000000, 5) (2000000, 8)
number of missing values in columns of ratings_movies_df: userId        0
movieId       0
rating        0
timestamp     0
year_x        0
title         0
genres        0
year_y       37
dtype: int64
total number of missing values in ratings_movies_df: 37

,userId,movieId,rating,timestamp,year_x,title,genres,year_y
0,1,2,3.5,2005-04-02 23:53:47,2005,Jumanji (1995),Adventure|Children|Fantasy,1995
1,1,29,3.5,2005-04-02 23:31:16,2005,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,1995
2,1,32,3.5,2005-04-02 23:33:39,2005,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,1995
3,1,47,3.5,2005-04-02 23:32:07,2005,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995
4,1,50,3.5,2005-04-02 23:29:40,2005,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995

# Fusion of genome_scores and genome_tags

In [ ]:
genome_scores_df = pd.read_parquet('../data/processed/genome_scores_df.parquet')
genome_tags_df = pd.read_parquet('../data/processed/genome_tags_df.parquet')
genome_df = genome_scores_df.merge(genome_tags_df, on="tagId", how="left")
display(genome_df.head(10))
print("number of missing values:", genome_df.isnull().sum().sum())

# Pivot of genome to movies_profile

In [ ]:
movies_profile_df = genome_df.pivot(index="movieId",columns = "tag",values = "relevance")
print("number of columns in movies_profile_df:", movies_profile_df.shape[1])
print("number of lines in movies_profile_df:", movies_profile_df.shape[0])
display(movies_profile_df.head(5))
print("number of missing values in movies_profile_df:", movies_profile_df.isnull().sum().sum())

number of columns in movies_profile_df: 1128
number of lines in movies_profile_df: 10381

tag,007,007 (series),18th century,1920s,1930s,1950s,1960s,1970s,1980s,19th century,...,world politics,world war i,world war ii,writer's life,writers,writing,wuxia,wwii,zombie,zombies
movieId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

number of missing values in movies_profile_df: 10671668

# Fusion between movies_ratings and movies_profile

In [ ]:
movies_ratings_profile_df = ratings_movies_df.merge(movies_profile_df, on="movieId", how="left")
display(movies_ratings_profile_df.head(5))

,userId,movieId,rating,timestamp,year_x,title,genres,year_y,007,007 (series),...,world politics,world war i,world war ii,writer's life,writers,writing,wuxia,wwii,zombie,zombies
0,1,2,3.5,2005-04-02 23:53:47,2005,Jumanji (1995),Adventure|Children|Fantasy,1995,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,29,3.5,2005-04-02 23:31:16,2005,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,1995,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,32,3.5,2005-04-02 23:33:39,2005,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,1995,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,47,3.5,2005-04-02 23:32:07,2005,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,50,3.5,2005-04-02 23:29:40,2005,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN